language: php

sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

# Test against these versions of WordPress.
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=5.4.2 WP_MULTISITE=0
    - WP_VERSION=5.3.4 WP_MULTISITE=0

matrix:
  include:
      - php: 7.1
        env: WP_VERSION=latest WP_MULTISITE=0
      - php: 7.1
        env: WP_VERSION=4.7.18 WP_MULTISITE=0
      - php: 5.6
        env: WP_VERSION=latest WP_MULTISITE=1

  exclude:
      - php: 7.4
        env: WP_VERSION=5.2.7 WP_MULTISITE=0
      - php: 7.4
        env: WP_VERSION=5.1.6 WP_MULTISITE=0
      - php: 7.4
        env: WP_VERSION=5.0.10 WP_MULTISITE=0

before_script:
  - |
    # Export Composer's global bin dir to PATH, but not on PHP 5.2
    if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
      composer config --list --global
      export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
    fi
  - |
    # Remove Xdebug for a huge performance increase
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    # Install WordPress and PHPUnit
        if [[ ! -z "$WP_VERSION" ]] ; then
          bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
          case "$TRAVIS_PHP_VERSION" in
            7.3|7.2|7.1|7.0|nightly)
              echo "Using PHPUnit 6.x"
              composer global require "phpunit/phpunit:^6"
              ;;
            5.6|5.5|5.4|5.3)
              echo "Using PHPUnit 4.x"
              composer global require "phpunit/phpunit:^4"
              ;;
            5.2)
              # Do nothing, use default PHPUnit 3.6.x
              echo "Using default PHPUnit, hopefully 3.6"
              ;;
            *)
              echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
              exit 1
              ;;
          esac
        fi
  - |
    # Install PHP_CodeSniffer if it's requested for this test
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    # Run PHPUnit in both single site and multisite mode
    if [[ ! -z "$WP_VERSION" && "$WP_TRAVISCI" != "phpcs" ]] ; then
      phpunit --verbose --coverage-clover=coverage.clover
      WP_MULTISITE=1 phpunit --verbose --coverage-clover=coverage.clover
    fi
  - |
    # Run PHP_CodeSniffer coding standards if it's requested for this test
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - develop
    - /^release\/.*$/
