language: php

sudo: false
dist: trusty

php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.9.8 WP_MULTISITE=0
- WP_VERSION=4.8.3 WP_MULTISITE=0
- WP_VERSION=4.7.7 WP_MULTISITE=0
- WP_VERSION=4.6.8 WP_MULTISITE=0
- WP_VERSION=4.5.11 WP_MULTISITE=0

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0
      dist: precise
    - php: 5.4
      env: WP_VERSION=4.7 WP_MULTISITE=0
      dist: precise
    - php: 5.4
      env: WP_VERSION=4.6 WP_MULTISITE=0
      dist: precise
    - php: 5.4
      env: WP_VERSION=4.5.3 WP_MULTISITE=0
      dist: precise
  exclude:
    - php: hhvm
      env: WP_VERSION=4.0 WP_MULTISITE=0

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
  if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
    composer global require "phpunit/phpunit=5.7.*"
  else
    composer global require "phpunit/phpunit=4.8.*"
  fi

script:
- if [[ $TRAVIS_PHP_VERSION != 'hhvm' && ( $TRAVIS_PHP_VERSION != '5.5'|| $WP_VERSION != 'latest' || $WP_MULTISITE != '0' ) ]];
  then phpenv config-rm xdebug.ini; fi
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]];
  then phpunit --coverage-clover=coverage.clover; else phpunit; fi

branches:
  only:
    - master
    - develop
    - /^release\/.*$/
